version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "5050:5050"
    environment:
      - DB_HOST=host.docker.internal # Biar bisa akses MySQL Laragon dari dalam Docker
    restart: always

  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: always